baseURL = "https://recetas.domains.uflib.ufl.edu/"
defaultContentLanguage = "es"
title = "Recetas"
theme = "Tale"
toc = true
paginate = 10000
sectionPagesMenu = "main"
[languages]
[languages.en]
title = "Recipes"
custom_title = "Recipes"
languageName = "English"
weight = 2
[languages.es]
title = "Recetas"
languageName = "español"
weight = 1
[taxonomies]
category = 'categories'
sources = "source"
ingredients = "ingredientes"
course = "plato"
tag = 'etiquettas'
[[related.indices]]
name = 'ingredientes'
weight = 100
[[related.indices]]
name = 'source'
weight = 100
[menu]
[[languages.es.menu.main]]
name = 'Inicio'
pre = "<i class='fa fa-heart'></i>"
url = '/'
weight = -110

  [[languages.es.menu.main]]
  name = 'Filtro'
  post = "<span class='alert'></span>"
pre = "<i class='fa fa-road'></i>"
url = '/filtro/'
weight = -100

  [[languages.en.menu.main]]
  name = 'Home'
  pre = "<i class='fa fa-heart'></i>"
url = '/'
weight = -110

[[languages.en.menu.main]]
name = 'Filter'
post = "<span class='alert'></span>"
pre = "<i class='fa fa-road'></i>"
url = '/filtro/'
weight = -100


