baseURL = "https://recetas.domains.uflib.ufl.edu/"
defaultContentLanguage = "es"
title = "Recetas"
theme = "Tale"
toc = true
paginate = 10000
sectionPagesMenu = "main"
[languages]
[languages.en]
title = "Recipes"
languageName = "English"
weight = 2
[languages.es]
title = "Recetas"
languageName = "Español"
weight = 1
[taxonomies]
sources = "source"
ingredients = "ingredientes"
course = "plato"
tag = 'etiquettas'
[[related.indices]]
name = 'ingredientes'
weight = 100
[[related.indices]]
name = 'source'
weight = 100
[menu]
[[languages.es.menu.main2]]
name = 'Inicio'
pre = "<i class='fa fa-heart'></i>"
url = '/'
weight = -110

  [[languages.es.menu.main2]]
  name = 'Filtro'
  post = "<span class='alert'></span>"
pre = "<i class='fa fa-road'></i>"
url = '/filtro/'
weight = -100

[[languages.es.menu.main2]]
name = 'Recetas'
post = "<span class='alert'></span>"
pre = "<i class='fa fa-road'></i>"
url = '/recetas/'
weight = -100

[[languages.es.menu.main2]]
name = 'Acerca'
pre = "<i class='fa fa-heart'></i>"
url = '/about'
weight = -100

  [[languages.en.menu.main2]]
  name = 'Home'
  pre = "<i class='fa fa-heart'></i>"
url = '/'
weight = -110

[[languages.en.menu.main2]]
name = 'Filter'
post = "<span class='alert'></span>"
pre = "<i class='fa fa-road'></i>"
url = '/filtro/'
weight = -100

[[languages.en.menu.main2]]
name = 'About'
pre = "<i class='fa fa-heart'></i>"
url = '/about'
weight = -100

[[languages.en.menu.main2]]
name = 'Recipes'
pre = "<i class='fa fa-heart'></i>"
url = '/recetas'
weight = -100
