baseURL = "https://stew.reclaim.hosting/"
defaultContentLanguage = "es"
title = "Recetas"
theme = "Tale"
toc = true
paginate = 10000
sectionPagesMenu = "main"
[taxonomies]
category = 'categories'
sources = "source"
ingredients = "ingredientes"
course = "plato"
tag = 'tags'
[[related.indices]]
name = 'ingredientes'
weight = 100
[[related.indices]]
name = 'source'
weight = 100
[menu]
[[menu.main]]
name = 'Home'
pre = "<i class='fa fa-heart'></i>"
url = '/'
weight = -110
[[menu.main]]
  name = 'Ingredientes'
  post = "<span class='alert'></span>"
  pre = "<i class='fa fa-road'></i>"
  url = '/ingredientes/'
  weight = -100
[[menu.main]]
  name = 'Plato'
  post = "<span class='alert'></span>"
  pre = "<i class='fa fa-road'></i>"
  url = '/plato/'
  weight = -100
